default_branch: "main"
versioning:
  default_major: 0
  default_minor: 0
  default_patch: 0
create_maintenance_branch: true
release_trigger:
  enable: false
  token: "bump-version"
channels:
  - name: "next"
    gates:
      workflows:
        enable: true
        required_workflows: ["*"]
      approvals:
        enable: false
        required_approvers: ["*"]
    house_keeping:
      delete_unpromoted_tags: 
      delete_unpromoted_branches: 
    release:
      create_release: false
      prerelease: true
